### ISSUE TITLE
(REF) MVP: Able to navigate to site

### ISSUE THREAD

**Issue by Joseph-WhiteSWE** [teamseven-2301/Internet-Dungeon-Crawler#10]

**Comment by AlexPetrovichJr** [comment]
FRONTEND: 
[ ] - Clickable links/items 
[ ] - Correct routes in React-Router
[ ] - Navbar with every page available (save for sensitive/Admin views)
[ ] - Slices with async thunks with axios calls

BACKEND:
[ ] - Server Routes working correctly
